"""
Sends Company Insights PDF reports via email.

Primary:  Resend API  (https://resend.com) — fast, reliable, zero SMTP config.
Fallback: SMTP        (Gmail / any provider)  — SMTP_ENABLED=True in .env.

Configure in .env:
    RESEND_API_KEY=re_xxxxxxxxxxxx
    RESEND_FROM=onboarding@resend.dev   # free tier; use your domain once verified

    # Only needed if RESEND_API_KEY is empty:
    SMTP_ENABLED=True
    SMTP_HOST=smtp.gmail.com
    SMTP_PORT=587
    SMTP_USER=you@gmail.com
    SMTP_PASS=xxxx xxxx xxxx xxxx
"""

import base64
import smtplib
import logging
import importlib
from typing import Any
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from datetime import datetime

from core.config import settings

logger = logging.getLogger(__name__)


# ── HTML email template ──────────────────────────────────────────────────────
SECTION_CONFIG = [
    ("PR & Announcements",        "pr",          "#3b82f6"),
    ("Podcast Appearances",       "podcasts",    "#a855f7"),
    ("Advertising Campaigns",     "ads",         "#f97316"),
    ("Influencer Collaborations", "influencers", "#10b981"),
]

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Sneak Intelligence Report</title>
  <style>
    body {{ margin:0; padding:0; background:#0f172a; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; color:#e2e8f0; }}
    .wrapper {{ max-width:600px; margin:0 auto; padding:32px 16px; }}
    .header {{ background:linear-gradient(135deg,#3b82f6 0%,#a855f7 100%); border-radius:16px; padding:32px; text-align:center; margin-bottom:24px; }}
    .header h1 {{ margin:0 0 8px; font-size:28px; font-weight:800; color:#fff; }}
    .header p  {{ margin:0; font-size:14px; color:rgba(255,255,255,.75); }}
    .notice {{ background:#1e293b; border:1px solid #334155; border-radius:12px; padding:20px; text-align:center; margin-bottom:24px; font-size:14px; color:#94a3b8; }}
    .card  {{ background:#1e293b; border-radius:12px; padding:24px; margin-bottom:16px; }}
    .card h2 {{ margin:0 0 16px; font-size:15px; font-weight:700; }}
    .card ul {{ margin:0; padding:0 0 0 16px; }}
    .card ul li {{ margin-bottom:10px; font-size:14px; line-height:1.6; color:#94a3b8; }}
    .no-data {{ font-style:italic; color:#475569; font-size:13px; }}
    .footer {{ text-align:center; font-size:12px; color:#475569; margin-top:32px; }}
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>{company_name}</h1>
      <p>Sneak Intelligence Report &mdash; {generated_at}</p>
    </div>
    <div class="notice">&#128206; A beautifully formatted <strong>PDF report</strong> is attached. Open it for a full branded view.</div>
    {sections_html}
    <div class="footer"><p>Generated by <strong>Sneak</strong><br/>Powered by OpenRouter AI &middot; Data via SearXNG</p></div>
  </div>
</body>
</html>
"""


def _build_html(company_name: str, insights: dict) -> str:
    sections_parts = []
    for label, key, colour in SECTION_CONFIG:
        items = insights.get(key, [])
        body = (
            "<ul>" + "".join(f"<li>{item}</li>" for item in items) + "</ul>"
            if items else '<p class="no-data">No data found for this category.</p>'
        )
        sections_parts.append(
            f'<div class="card" style="border-left:4px solid {colour}">'
            f'<h2 style="color:{colour}">{label}</h2>{body}</div>'
        )
    return HTML_TEMPLATE.format(
        company_name=company_name,
        generated_at=datetime.now().strftime("%B %d, %Y"),
        sections_html="\n".join(sections_parts),
    )


# ── Resend delivery (primary) ────────────────────────────────────────────────
def _send_via_resend(to_email: str, company_name: str, insights: dict, pdf_bytes: bytes) -> bool:
    try:
        resend: Any = importlib.import_module("resend")  # pip install resend
        resend.api_key = settings.RESEND_API_KEY

        safe_name = company_name.replace(" ", "_").lower()
        pdf_b64 = base64.b64encode(pdf_bytes).decode()

        params = {
            "from": settings.RESEND_FROM,
            "to": [to_email],
            "subject": f"Your {company_name} Insights Report is Ready",
            "html": _build_html(company_name, insights),
            "attachments": [
                {
                    "filename": f"{safe_name}_insights_report.pdf",
                    "content": pdf_b64,
                }
            ],
        }

        result = resend.Emails.send(params)
        logger.info(f"[EmailService] Resend delivery → {to_email}  id={result.get('id')}")
        return True

    except Exception as exc:
        logger.error(f"[EmailService] Resend failed: {exc}")
        return False


# ── SMTP fallback ────────────────────────────────────────────────────────────
def _send_via_smtp(to_email: str, company_name: str, insights: dict, pdf_bytes: bytes) -> bool:
    if not settings.SMTP_ENABLED:
        logger.warning("[EmailService] SMTP_ENABLED=False — skipping SMTP fallback.")
        return False
    if not settings.SMTP_USER or not settings.SMTP_PASS:
        logger.error("[EmailService] SMTP credentials not configured.")
        return False

    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"Your {company_name} Insights Report is Ready"
    msg["From"]    = settings.SMTP_FROM or settings.SMTP_USER
    msg["To"]      = to_email
    msg.attach(MIMEText(_build_html(company_name, insights), "html", "utf-8"))

    pdf_part = MIMEBase("application", "pdf")
    pdf_part.set_payload(pdf_bytes)
    encoders.encode_base64(pdf_part)
    safe_name = company_name.replace(" ", "_").lower()
    pdf_part.add_header("Content-Disposition", "attachment",
                        filename=f"{safe_name}_insights_report.pdf")
    msg.attach(pdf_part)

    try:
        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=20) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.login(settings.SMTP_USER, settings.SMTP_PASS)
            smtp.sendmail(settings.SMTP_USER, to_email, msg.as_string())
        logger.info(f"[EmailService] SMTP delivery → {to_email}")
        return True
    except Exception as exc:
        logger.error(f"[EmailService] SMTP failed: {exc}")
        return False


# ── Public interface ─────────────────────────────────────────────────────────
class EmailService:
    def send_insights_report(self, to_email: str, insights: dict, pdf_bytes: bytes) -> bool:
        """
        Deliver a PDF report by email.
        Uses Resend if RESEND_API_KEY is set, otherwise falls back to SMTP.
        """
        company_name = insights.get("companyName", "Company")

        if settings.RESEND_API_KEY:
            return _send_via_resend(to_email, company_name, insights, pdf_bytes)
        else:
            logger.warning("[EmailService] RESEND_API_KEY not set — trying SMTP fallback.")
            return _send_via_smtp(to_email, company_name, insights, pdf_bytes)


